name: Development Environment

on:
  push:
    branches:
    - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Notify Slack
      if: success()
      id: slack
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        channel_id: C01D16VJ84C
        status: BUILD STARTED
        color: warning

    - name: Setup Nodejs
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Cache dependencies
      id: node-cache
      uses: actions/cache@v2
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies
      if: steps.node-cache.outputs.cache-hit != 'true'
      run: npm ci

    - name: Build
      run: npm run build
      env:
        CI: false
        SKIP_PREFLIGHT_CHECK: true
        REACT_APP_ENV: 'development'
        REACT_APP_HTML_TITLE: 'BarnBridge Kovan'

        REACT_APP_WEB3_CHAIN_ID: 42
        REACT_APP_WEB3_POLLING_INTERVAL: 12000
        REACT_APP_WEB3_RPC_WSS_URL: 'wss://kovan.infura.io/ws/v3/6c58700fe84943eb83c4cd5c23dff3d8'
        REACT_APP_WEB3_RPC_HTTPS_URL: 'https://kovan.infura.io/v3/6c58700fe84943eb83c4cd5c23dff3d8'
        REACT_APP_WEB3_PORTIS_APP_ID: 'b0b0f776-bbf6-458c-a175-6483e0c452b7'
        REACT_APP_WEB3_WALLET_CONNECT_BRIDGE: 'https://bridge.walletconnect.org'
        REACT_APP_WEB3_COINBASE_APP_NAME: 'barnbridge'
        REACT_APP_WEB3_TREZOR_EMAIL: 'bogdan@barnbridge.com'
        REACT_APP_WEB3_TREZOR_APP_URL: 'https://app.barnbridge.com/'
        REACT_APP_ETHERSCAN_API_KEY: '4RSJUUZQFMXUAUUJP5FI5UR5U59N7UIA32'

        REACT_APP_TOKEN_WBTC_ADDR: '0x2260fac5e5542a773aa44fbcfedf7c193bc2c599'
        REACT_APP_TOKEN_RENBTC_ADDR: '0xEB4C2781e4ebA804CE9a9803C67d0893436bB27D'
        REACT_APP_TOKEN_WETH_ADDR: '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2'
        REACT_APP_TOKEN_BOND_ADDR: '0x521EE0CeDbed2a5A130B9218551fe492C5c402e4'
        REACT_APP_TOKEN_USDC_ADDR: '0x4A69d0F05c8667B993eFC2b500014AE1bC8fD958'
        REACT_APP_TOKEN_DAI_ADDR: '0xEa8BE82DF1519D4a25E2539bcA0342a1203CD591'
        REACT_APP_TOKEN_SUSD_ADDR: '0xED159a31184ADADC5c28CE5D9e4822ea2b0B6ef9'
        REACT_APP_TOKEN_GUSD_ADDR: '0x056fd409e1d7a124bd7017459dfea2f387b6d5cd'
        REACT_APP_TOKEN_USDT_ADDR: '0xdac17f958d2ee523a2206206994597c13d831ec7'
        REACT_APP_TOKEN_UNIV2_ADDR: '0xe594D2B3BeA4454D841e5b616627dCA6A5D7aCF1'
        REACT_APP_TOKEN_BBC_USDC_ADDR: '0x2327c862e8770e10f63eef470686ffd2684a0092'
        REACT_APP_TOKEN_BBC_DAI_ADDR: '0xebf32075b5ee6e9aff265d3ec6c69a2b381b61b1'
        REACT_APP_TOKEN_BBA_DAI_ADDR: '0xdfcb1c9d8209594cbc39745b274e9171ba4fd343'
        REACT_APP_TOKEN_STKAAVE_ADDR: '0xf2fbf9a6710afda1c4aab2e922de9d69e0c97fd2'
        REACT_APP_TOKEN_BBA_USDC_ADDR: ''
        REACT_APP_TOKEN_BBA_GUSD_ADDR: ''
        REACT_APP_TOKEN_AUSDC_ADDR: '0xBcca60bB61934080951369a648Fb03DF4F96263C'
        REACT_APP_TOKEN_ADAI_ADDR: '0x028171bCA77440897B824Ca71D1c56caC55b68A3'
        REACT_APP_TOKEN_AUSDT_ADDR: '0x3Ed3B47Dd13EC9a98b44e6204A523E766B225811'
        REACT_APP_TOKEN_AGUSD_ADDR: '0xD37EE7e4f452C6638c96536e68090De8cBcdb583'

        REACT_APP_FEED_BTC_ADDR: '0xF4030086522a5bEEa4988F8cA5B36dbC97BeE88c'
        REACT_APP_FEED_ETH_ADDR: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
        REACT_APP_FEED_BOND_ADDR: '0xe594D2B3BeA4454D841e5b616627dCA6A5D7aCF1'
        REACT_APP_FEED_USDC_ADDR: '0x8fFfFfd4AfB6115b954Bd326cbe7B4BA576818f6'
        REACT_APP_FEED_DAI_ADDR: '0xAed0c38402a5d19df6E4c03F4E2DceD6e29c1ee9'
        REACT_APP_FEED_SUSD_ADDR: '0x8e0b7e6062272B5eF4524250bFFF8e5Bd3497757'
        REACT_APP_FEED_USDT_ADDR: '0x4e58ab12d2051ea2068e78e4fcee7ddee6785848'
        REACT_APP_FEED_UNIV2_ADDR: '0xe594D2B3BeA4454D841e5b616627dCA6A5D7aCF1'
        REACT_APP_FEED_BBC_USDC_ADDR: '0x2327c862e8770e10f63eef470686ffd2684a0092'
        REACT_APP_FEED_BBC_DAI_ADDR: '0xebf32075b5ee6e9aff265d3ec6c69a2b381b61b1'

        REACT_APP_CONTRACT_YF_STAKING_ADDR: '0x618bB8f9e76f2982B8783e6AA09bC930c65f0AC8'
        REACT_APP_CONTRACT_YF_STABLE_ADDR: '0xf865D61e3791ef6C202c62b79f42de3f9e9AC8b3'
        REACT_APP_CONTRACT_YF_UNILP_ADDR: '0x4e600bd65AE29d12ab22EE0384bD472F24d7aEa6'
        REACT_APP_CONTRACT_YF_BOND_ADDR: '0x82B568C2E5159ba20358aF425E92ac96345c9C9a'
        REACT_APP_CONTRACT_DAO_GOVERNANCE_ADDR: '0x930e52B96320d7dBbfb6be458e5EE0Cd3E5E5Dac'
        REACT_APP_CONTRACT_DAO_BARN_ADDR: '0x0DEc9fdb535eB45cef986F1129bb234578F8BD20'
        REACT_APP_CONTRACT_DAO_REWARD_ADDR: '0xc2d3B609EB967c72AfF4731Ca96375f26926B1F9'

        REACT_APP_DAO_ACTIVATION_THRESHOLD: 400000

        REACT_APP_BASE_API_URL: 'https://dev.api.barnbridge.com'

    - name: Save artifacts
      uses: actions/upload-artifact@v2
      with:
        name: frontend
        path: build

    - name: Notify Slack success
      if: success()
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        message_id: ${{ steps.slack.outputs.message_id }}
        channel_id: C01D16VJ84C
        status: BUILD SUCCESSFUL
        color: good

    - name: Notify Slack failure
      if: failure()
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        message_id: ${{ steps.slack.outputs.message_id }}
        channel_id: C01D16VJ84C
        status: BUILD FAILED
        color: danger

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Notify Slack
      if: success()
      id: slack
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        channel_id: C01D16VJ84C
        status: DEPLOYMENT STARTED
        color: warning

    - name: Get artifacts
      uses: actions/download-artifact@v2
      with:
        name: frontend

    - name: Configure AWS credetials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy static site to S3
      run: ls -l && aws s3 sync . s3://dev-devappbarnbridgecom-origin --delete

    - name: Invalidate CloudFront cache
      run: |
        #!/usr/bin/env bash
        set -eou pipefail

        CF_DIST_ID=$(aws cloudfront list-distributions --query "DistributionList.Items[?Aliases.Items!=null] | [?contains(Aliases.Items, 'dev.app.barnbridge.com')].Id | [0]" | tr -d \")
        echo "Clearing cache for ${CF_DIST_ID}..."
        CF_INVALIDATION_ID=$(aws cloudfront create-invalidation --distribution-id ${CF_DIST_ID} --paths "/*" | jq -r '.Invalidation.Id')
        while [ $(aws cloudfront get-invalidation --distribution-id ${CF_DIST_ID} --id ${CF_INVALIDATION_ID} | jq -r '.Invalidation.Status') != "Completed" ]; do
          echo "CF_DIST_ID=${CF_DIST_ID} CF_INVALIDATION_ID=${CF_INVALIDATION_ID}: Waiting for CloudFront cache invalidation to complete..."
          sleep 5
        done

    - name: Notify Slack success
      if: success()
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        message_id: ${{ steps.slack.outputs.message_id }}
        channel_id: C01D16VJ84C
        status: DEPLOYMENT SUCCESSFUL
        color: good

    - name: Notify Slack failure
      if: failure()
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        message_id: ${{ steps.slack.outputs.message_id }}
        channel_id: C01D16VJ84C
        status: DEPLOYMENT FAILED
        color: danger
