name: Live Environment

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Notify Slack
        if: success()
        id: slack
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel_id: C01D16VJ84C
          status: BUILD STARTED
          color: warning

      - name: Setup Nodejs
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Cache dependencies
        id: node-cache
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Build
        run: npm run build
        env:
          CI: false
          SKIP_PREFLIGHT_CHECK: true
          REACT_APP_ENV: 'production'

          REACT_APP_GOERLI_INFURA_RPC_KEY: ${{ secrets.GOERLI_INFURA_RPC_KEY }}
          REACT_APP_GOERLI_ETHERSCAN_EXPLORER_KEY: ${{ secrets.GOERLI_ETHERSCAN_EXPLORER_KEY }}

          REACT_APP_KOVAN_INFURA_RPC_KEY: ${{ secrets.KOVAN_INFURA_RPC_KEY }}
          REACT_APP_KOVAN_ETHERSCAN_EXPLORER_KEY: ${{ secrets.KOVAN_ETHERSCAN_EXPLORER_KEY }}

          REACT_APP_MAINNET_INFURA_RPC_KEY: ${{ secrets.MAINNET_INFURA_RPC_KEY }}
          REACT_APP_MAINNET_ETHERSCAN_EXPLORER_KEY: ${{ secrets.MAINNET_ETHERSCAN_EXPLORER_KEY }}

          REACT_APP_MUMBAI_INFURA_RPC_KEY: ${{ secrets.MUMBAI_INFURA_RPC_KEY }}
          REACT_APP_MUMBAI_ETHERSCAN_EXPLORER_KEY: ${{ secrets.MUMBAI_ETHERSCAN_EXPLORER_KEY }}

          REACT_APP_POLYGON_INFURA_RPC_KEY: ${{ secrets.POLYGON_INFURA_RPC_KEY }}
          REACT_APP_POLYGON_ETHERSCAN_EXPLORER_KEY: ${{ secrets.POLYGON_ETHERSCAN_EXPLORER_KEY }}

          REACT_APP_TESTNET_INFURA_RPC_KEY: ${{ secrets.TESTNET_INFURA_RPC_KEY }}
          REACT_APP_TESTNET_ETHERSCAN_EXPLORER_KEY: ${{ secrets.TESTNET_ETHERSCAN_EXPLORER_KEY }}

      - name: Save artifacts
        uses: actions/upload-artifact@v2
        with:
          name: prod-frontend
          path: build

      - name: Notify Slack success
        if: success()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          message_id: ${{ steps.slack.outputs.message_id }}
          channel_id: C01D16VJ84C
          status: BUILD SUCCESSFUL
          color: good

      - name: Notify Slack failure
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          message_id: ${{ steps.slack.outputs.message_id }}
          channel_id: C01D16VJ84C
          status: BUILD FAILED
          color: danger

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Notify Slack
        if: success()
        id: slack
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel_id: C01D16VJ84C
          status: DEPLOYMENT STARTED
          color: warning

      - name: Get artifacts
        uses: actions/download-artifact@v2
        with:
          name: prod-frontend

      - name: Configure AWS credetials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy static site to S3
        run: ls -l && aws s3 sync . s3://prod-appbarnbridgecom-origin --delete

      - name: Invalidate CloudFront cache
        run: |
          #!/usr/bin/env bash
          set -euo pipefail

          CF_DIST_ID=$(aws cloudfront list-distributions --query "DistributionList.Items[?Aliases.Items!=null] | [?contains(Aliases.Items, 'app.barnbridge.com')].Id | [0]" | tr -d \")
          echo "Clearing cache for ${CF_DIST_ID}..."
          CF_INVALIDATION_ID=$(aws cloudfront create-invalidation --distribution-id ${CF_DIST_ID} --paths "/*" | jq -r '.Invalidation.Id')
          while [ $(aws cloudfront get-invalidation --distribution-id ${CF_DIST_ID} --id ${CF_INVALIDATION_ID} | jq -r '.Invalidation.Status') != "Completed" ]; do
            echo "CF_DIST_ID=${CF_DIST_ID} CF_INVALIDATION_ID=${CF_INVALIDATION_ID}: Waiting for CloudFront cache invalidation to complete..."
            sleep 5
          done

      - name: Notify Slack success
        if: success()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          message_id: ${{ steps.slack.outputs.message_id }}
          channel_id: C01D16VJ84C
          status: DEPLOYMENT SUCCESSFUL
          color: good

      - name: Notify Slack failure
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          message_id: ${{ steps.slack.outputs.message_id }}
          channel_id: C01D16VJ84C
          status: DEPLOYMENT FAILED
          color: danger
